version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '3000:3000'